modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "immersive_cursedness"
version = "${version}"
displayName = "ImmersiveCursednessReforged"
authors="TeamPotato"
description = '''

'''